version: "3.3"

services:
  db:
    image: mysql:5.7
    volumes:
      - mysql:/var/lib/mysql
    restart: always
    ports:
      - 3305:3306
    env_file: ./mysqldb.env
    container_name: mysqldb
  web-server:
    image: php:latest-apache
    volumes:
      - webserver:/var/www/html
    restart: always
    depends_on: db
    ports:
      - 8090:80
    env_file: ./web-server.env
    container_name: webserver
