version: "3.3"

services:
  db:
    container_name: mysql
    image: mysql:5.7
    volumes:
      - ../mysqldb:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    env_file: ./mysqldb.env
    container_name: mysqldb
  web-server:
    container_name: webserver
    image: polinux/httpd-php:php72
    volumes:
      - ../design/:/var/www/html/
    restart: always
    depends_on:
      - db
    ports:
      - 80:80
    env_file: ./web-server.env
    container_name: webserver
